// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPMPqI7EE65CJmTOj3SUEq1nqVi5qtSvA',
    appId: '1:615723229723:web:702e9a405a0bc0c460cebe',
    messagingSenderId: '615723229723',
    projectId: 'fir-1248e',
    authDomain: 'fir-1248e.firebaseapp.com',
    storageBucket: 'fir-1248e.appspot.com',
    measurementId: 'G-RW65KHJDJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8gXE3VHIXomFg83rIcDh1j6CAI7iyRRU',
    appId: '1:615723229723:android:dda2eec3fecdc4cb60cebe',
    messagingSenderId: '615723229723',
    projectId: 'fir-1248e',
    storageBucket: 'fir-1248e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWSjHSUcG0dQPg9yDjz_ZqOTHjkjJr69k',
    appId: '1:615723229723:ios:c3acde2648b7cd2060cebe',
    messagingSenderId: '615723229723',
    projectId: 'fir-1248e',
    storageBucket: 'fir-1248e.appspot.com',
    androidClientId: '615723229723-4oig3g6p2esk9kop8q1hoqjo13pb64qp.apps.googleusercontent.com',
    iosClientId: '615723229723-m942n3kqk2g4sao3uh1jujrqgrd1ouoa.apps.googleusercontent.com',
    iosBundleId: 'com.tiar.google',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWSjHSUcG0dQPg9yDjz_ZqOTHjkjJr69k',
    appId: '1:615723229723:ios:ab2d2e3ecc1b6ab260cebe',
    messagingSenderId: '615723229723',
    projectId: 'fir-1248e',
    storageBucket: 'fir-1248e.appspot.com',
    androidClientId: '615723229723-4oig3g6p2esk9kop8q1hoqjo13pb64qp.apps.googleusercontent.com',
    iosClientId: '615723229723-jcvirl801sa151velucqtqupmb9q1grq.apps.googleusercontent.com',
    iosBundleId: 'com.tiar.google.RunnerTests',
  );
}
